### ISSUE TITLE
Wrong "eta" in \Greek

### ISSUE THREAD

**Issue by pmav99** [scmbradley/moreenum#1]
I think that this is how it should be:

``` diff
-  \or Z\or E\or\Theta\or I\or K\or\Lambda
+  \or Z\or H\or\Theta\or I\or K\or\Lambda
```

https://github.com/scmbradley/moreenum/blob/master/moreenum.sty#L77

**Comment by scmbradley** [comment]
You're absolutely right.

I hope to fix this later this week.

**Comment by scmbradley** [comment]
This is fixed now. I'll send a new version to CTAN once I've made some further modifications.
