### ISSUE TITLE
Capitalization command errors

### ISSUE THREAD

**Issue by matthewcobb** [scmbradley/moreenum#2]
Issues with using the capitalise macros:

```
\Nwords{chapter} - only command that works
\NWORDS{chapter} - error "undefined control sequence"
\nwords{chapter} - error "undefined control sequence"
```

**Comment by scmbradley** [comment]
@matthewcobb could you include the whole error message (or the whole log file) please, and perhaps a minimal example illustrating the problem. It's still working fine on my setup.
